### ISSUE TITLE
Doco: Broken link to more info

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/gonexus#2]
near the bottom of the README.md, the link below is broken, and I wasn't sure where it should actually point to:

See the [documentation](https://godoc.org/github.com/sonatype-nexus-community/gonexus/iq/webhooks#example-Listen) for a full example showing other event types.

**Comment by HokieGeek** [comment]
Thank you. This is what happens when you change namespaces :)

https://github.com/sonatype-nexus-community/gonexus/commit/bf966fe90ef119dddb32f84a70ce26ada5709f61
